
package com.rci.omega2.async.service.ws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@SuppressWarnings("serial")
@WebFault(name = "AsyncUnexpectedException", targetNamespace = "http://ws.service.async.omega2.rci.com/")
public class AsyncUnexpectedException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AsyncUnexpectedException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AsyncUnexpectedException_Exception(String message, AsyncUnexpectedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AsyncUnexpectedException_Exception(String message, AsyncUnexpectedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.rci.omega2.async.service.ws.client.AsyncUnexpectedException
     */
    public AsyncUnexpectedException getFaultInfo() {
        return faultInfo;
    }

}
