
package com.rci.omega2.async.service.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SalesmanCommunicationService", targetNamespace = "http://ws.service.async.omega2.rci.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SalesmanCommunicationService {


    /**
     * 
     * @param request
     * @throws AsyncUnexpectedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "sendMessageSalesman", targetNamespace = "http://ws.service.async.omega2.rci.com/", className = "com.rci.omega2.async.service.ws.client.SendMessageSalesman")
    @ResponseWrapper(localName = "sendMessageSalesmanResponse", targetNamespace = "http://ws.service.async.omega2.rci.com/", className = "com.rci.omega2.async.service.ws.client.SendMessageSalesmanResponse")
    public void sendMessageSalesman(
        @WebParam(name = "request", targetNamespace = "")
        SalesmanCommunicationRequest request)
        throws AsyncUnexpectedException_Exception
    ;

}
